In [1]:
import numpy as np


In [2]:
print("NumPy version:", np.__version__) #version
np.show_config() #configuración

NumPy version: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jaime/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/jaime/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jaime/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/jaime/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jaime/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/jaime/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jaime/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/User

In [3]:
a = np.random.random ((2, 3, 5))

In [4]:
b = np.ones((5, 2 ,3))

In [5]:
print(a.size)
print(b.size)
print((True if a.size == b.size else False ))

30
30
True


In [9]:
try:
    print(a + b)
except ValueError:
    print(a.shape)
    print(b.shape)
    print(f'a and b have not the same shape')

(2, 3, 5)
(5, 2, 3)
a and b have not the same shape


In [16]:
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [14]:
d = a + c

In [20]:
print(f'esto es a: ', '\n', a)
print(f'esto es d: ', '\n', d)

esto es a:  
 [[[0.4076668  0.37009672 0.03855466 0.35632575 0.8099741 ]
  [0.22610928 0.49032765 0.79089587 0.82088758 0.85387235]
  [0.18899155 0.20514873 0.83263063 0.43839627 0.88364601]]

 [[0.84305738 0.64888127 0.96172118 0.48373832 0.57282201]
  [0.29929253 0.67679003 0.97750864 0.25373678 0.38605109]
  [0.62258662 0.2017159  0.90898593 0.82192755 0.32751557]]]
esto es d:  
 [[[1.4076668  1.37009672 1.03855466 1.35632575 1.8099741 ]
  [1.22610928 1.49032765 1.79089587 1.82088758 1.85387235]
  [1.18899155 1.20514873 1.83263063 1.43839627 1.88364601]]

 [[1.84305738 1.64888127 1.96172118 1.48373832 1.57282201]
  [1.29929253 1.67679003 1.97750864 1.25373678 1.38605109]
  [1.62258662 1.2017159  1.90898593 1.82192755 1.32751557]]]


In [28]:
e = a * c
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [27]:
print(True if np.array_equal(a, e) else False)

True


In [29]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [30]:
f = np.empty((2, 3, 5))
print(f'This is f: ', '\n', f)

This is f:  
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [32]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [49]:
f = np.where((d > d_min) & (d < d_mean), 25, f)
f = np.where((d > d_mean) & (d < d_max), 75, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d == d_min, 0, f)
f = np.where(d == d_max, 100, f)

  #numpy.where(condición, x, y)          

In [50]:
print(f)

[[[ 25.  25.   0.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25.  75. 100.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]
