In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [6]:
#2. Print the NUMPY version and the configuration.
np.__version__
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nico/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nico/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nico/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nico/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX51

In [14]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


a = np.random.random((2,3,5))




In [15]:
#4. Print a.
print(a)

[[[0.86305707 0.60039212 0.10728632 0.21636175 0.29493277]
  [0.21421307 0.45641288 0.4463366  0.80879057 0.59301495]
  [0.08017096 0.06543144 0.59689178 0.86836545 0.15359413]]

 [[0.55537873 0.93662025 0.41031871 0.99055263 0.49174226]
  [0.14169151 0.65228476 0.48092928 0.13111728 0.98691454]
  [0.49934946 0.259726   0.65832005 0.64323228 0.28420753]]]


In [27]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,3,2))

In [28]:
#6. Print b.
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [29]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(b.size)
print(a.size)
#Yes

30
30


In [30]:
#8. Are you able to add a and b? Why or why not?

# no, diferent dimensions
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [31]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.T

In [45]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c

In [55]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
# they now share dimensions and therefore can be operated with each other

[[[0.86305707 0.60039212 0.10728632 0.21636175 0.29493277]
  [0.21421307 0.45641288 0.4463366  0.80879057 0.59301495]
  [0.08017096 0.06543144 0.59689178 0.86836545 0.15359413]]

 [[0.55537873 0.93662025 0.41031871 0.99055263 0.49174226]
  [0.14169151 0.65228476 0.48092928 0.13111728 0.98691454]
  [0.49934946 0.259726   0.65832005 0.64323228 0.28420753]]]
[[[1.86305707 1.60039212 1.10728632 1.21636175 1.29493277]
  [1.21421307 1.45641288 1.4463366  1.80879057 1.59301495]
  [1.08017096 1.06543144 1.59689178 1.86836545 1.15359413]]

 [[1.55537873 1.93662025 1.41031871 1.99055263 1.49174226]
  [1.14169151 1.65228476 1.48092928 1.13111728 1.98691454]
  [1.49934946 1.259726   1.65832005 1.64323228 1.28420753]]]


In [56]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [57]:
#13. Does e equal to a? Why or why not?
a == e
# yes because c is a mtrix with values of 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [64]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [65]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))


In [70]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            
            
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i, j, k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i, j, k] = 75
            elif d[i,j,k]== d_mean:
                f[i, j, k] = 50
            elif d[i,j,k] == d_min:
                f[i, j, k] = 0
            elif d[i,j,k] == d_max:
                f[i, j, k] = 100

print(f)    
    

[[[ 75.  75.  25.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.   0.  75.  75.  25.]]

 [[ 75.  75.  25. 100.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


In [71]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f)
     

[[[1.86305707 1.60039212 1.10728632 1.21636175 1.29493277]
  [1.21421307 1.45641288 1.4463366  1.80879057 1.59301495]
  [1.08017096 1.06543144 1.59689178 1.86836545 1.15359413]]

 [[1.55537873 1.93662025 1.41031871 1.99055263 1.49174226]
  [1.14169151 1.65228476 1.48092928 1.13111728 1.98691454]
  [1.49934946 1.259726   1.65832005 1.64323228 1.28420753]]]
[[[ 75.  75.  25.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.   0.  75.  75.  25.]]

 [[ 75.  75.  25. 100.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""