In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.23.5


In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
#3. print a

'''
3 ways: using np.random.random, np.random.rand or np.random.randint
''''''

In [12]:
a = np.random.random((2, 3, 5))

In [14]:
print(a)

[[[0.5772456  0.20023356 0.6653412  0.94582991 0.70852848]
  [0.71923726 0.39907429 0.7483599  0.49107025 0.31299289]
  [0.15422283 0.4157734  0.73540287 0.35185291 0.28878163]]

 [[0.21606519 0.70524666 0.9662316  0.16981042 0.77166459]
  [0.81980578 0.23637959 0.55219397 0.95327106 0.18188054]
  [0.02508766 0.30616373 0.36463332 0.79198006 0.17900556]]]


In [6]:
a = [[[random.random() for _ in range(5)] for _ in range(3)] for _ in range(2)]

print(a)

NameError: name 'random' is not defined

In [7]:
import random

a = [[[random.random() for _ in range(5)] for _ in range(3)] for _ in range(2)]

In [8]:
a

[[[0.3248316382941928,
   0.4482169982498073,
   0.7401821105169928,
   0.03732870661449206,
   0.3295054388043862],
  [0.37859246581672834,
   0.009131179009482682,
   0.20544980157152515,
   0.9191769448610765,
   0.2804279364895691],
  [0.6648629917710193,
   0.9753003215741111,
   0.6628761544817475,
   0.7895823303050499,
   0.17314867187840566]],
 [[0.695164556144374,
   0.43363273332901897,
   0.258671826000459,
   0.4567163099222725,
   0.6238146759041221],
  [0.09693671399256898,
   0.640499744270402,
   0.5528454586239099,
   0.8425830129195369,
   0.029019990059022338],
  [0.8456006044860981,
   0.015121268844961677,
   0.4807758443398318,
   0.5767198057250296,
   0.9123122185944466]]]

In [9]:
a = np.random.rand(2, 3, 5)

a

array([[[0.31246078, 0.18092144, 0.76874429, 0.92791979, 0.63274048],
        [0.03065519, 0.8839407 , 0.83591889, 0.43412378, 0.59734945],
        [0.03827372, 0.28645149, 0.53429951, 0.91394214, 0.11729827]],

       [[0.32210136, 0.82246308, 0.23720156, 0.16543573, 0.55827898],
        [0.3035851 , 0.45516142, 0.50147683, 0.30661755, 0.08195933],
        [0.2620728 , 0.58532094, 0.55452207, 0.5332889 , 0.58372258]]])

In [10]:
a = np.random.randint(0, 10, (2, 3, 5))

a

array([[[1, 0, 5, 5, 9],
        [0, 7, 6, 8, 0],
        [6, 3, 2, 5, 9]],

       [[8, 4, 7, 9, 9],
        [2, 6, 1, 7, 0],
        [2, 4, 1, 7, 9]]])

In [13]:
print(a)

[[[0.5772456  0.20023356 0.6653412  0.94582991 0.70852848]
  [0.71923726 0.39907429 0.7483599  0.49107025 0.31299289]
  [0.15422283 0.4157734  0.73540287 0.35185291 0.28878163]]

 [[0.21606519 0.70524666 0.9662316  0.16981042 0.77166459]
  [0.81980578 0.23637959 0.55219397 0.95327106 0.18188054]
  [0.02508766 0.30616373 0.36463332 0.79198006 0.17900556]]]


In [ ]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#6. Print b

In [15]:
b = np.ones((5, 2, 3))

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [18]:
 # use .size
    
a.size

30

In [19]:
b.size

30

In [ ]:
Both have same size. 

In [ ]:
#8. Are you able to add a and b? Why or why not? 
'''No, since they are not compatible (shape is diferent). It needs to be transposed 'b' into 'a' shape.
''

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [22]:
b = np.transpose(b, (1, 2, 0))
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [26]:
c = a + b

In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [27]:
d = a + c
d
# they are compatible because theirs' shapes are the same.

array([[[2.1544912 , 1.40046713, 2.33068239, 2.89165982, 2.41705697],
        [2.43847451, 1.79814857, 2.4967198 , 1.98214049, 1.62598577],
        [1.30844566, 1.8315468 , 2.47080574, 1.70370583, 1.57756326]],

       [[1.43213038, 2.41049333, 2.93246319, 1.33962085, 2.54332918],
        [2.63961156, 1.47275918, 2.10438795, 2.90654212, 1.36376107],
        [1.05017531, 1.61232746, 1.72926664, 2.58396013, 1.35801112]]])

In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
'''''
d= a + a + b 
d = 2*a + b

In [29]:
a

array([[[0.5772456 , 0.20023356, 0.6653412 , 0.94582991, 0.70852848],
        [0.71923726, 0.39907429, 0.7483599 , 0.49107025, 0.31299289],
        [0.15422283, 0.4157734 , 0.73540287, 0.35185291, 0.28878163]],

       [[0.21606519, 0.70524666, 0.9662316 , 0.16981042, 0.77166459],
        [0.81980578, 0.23637959, 0.55219397, 0.95327106, 0.18188054],
        [0.02508766, 0.30616373, 0.36463332, 0.79198006, 0.17900556]]])

In [30]:
d

array([[[2.1544912 , 1.40046713, 2.33068239, 2.89165982, 2.41705697],
        [2.43847451, 1.79814857, 2.4967198 , 1.98214049, 1.62598577],
        [1.30844566, 1.8315468 , 2.47080574, 1.70370583, 1.57756326]],

       [[1.43213038, 2.41049333, 2.93246319, 1.33962085, 2.54332918],
        [2.63961156, 1.47275918, 2.10438795, 2.90654212, 1.36376107],
        [1.05017531, 1.61232746, 1.72926664, 2.58396013, 1.35801112]]])

In [31]:
values(a)

NameError: name 'values' is not defined

In [ ]:
#12. Multiply a and c. Assign the result to e.

In [33]:
e = np.multiply(a, c)

In [34]:
print(e)


array([[[0.91045809, 0.24032704, 1.1080201 , 1.84042413, 1.2105411 ],
        [1.23653949, 0.55833457, 1.30840244, 0.73222023, 0.41095743],
        [0.17800751, 0.58864092, 1.27622026, 0.47565339, 0.37217646]],

       [[0.26274935, 1.20261952, 1.8998351 , 0.198646  , 1.36713083],
        [1.49188729, 0.2922549 , 0.85711216, 1.86199677, 0.21496107],
        [0.02571705, 0.39989996, 0.49759077, 1.41921249, 0.21104855]]])

In [44]:
#13. Does e equal to a? Why or why not?
"""
They are not equals, since their corresponding 
elements don´t have the same values.
"""


'\nThey are not equals, since their corresponding \nelements don´t have the same values.\n'

In [35]:
a

array([[[0.5772456 , 0.20023356, 0.6653412 , 0.94582991, 0.70852848],
        [0.71923726, 0.39907429, 0.7483599 , 0.49107025, 0.31299289],
        [0.15422283, 0.4157734 , 0.73540287, 0.35185291, 0.28878163]],

       [[0.21606519, 0.70524666, 0.9662316 , 0.16981042, 0.77166459],
        [0.81980578, 0.23637959, 0.55219397, 0.95327106, 0.18188054],
        [0.02508766, 0.30616373, 0.36463332, 0.79198006, 0.17900556]]])

In [37]:
a.shape

(2, 3, 5)

In [38]:
e.shape

(2, 3, 5)

In [39]:
a+e

array([[[1.48770369, 0.44056061, 1.7733613 , 2.78625404, 1.91906958],
        [1.95577675, 0.95740886, 2.05676235, 1.22329048, 0.72395032],
        [0.33223035, 1.00441432, 2.01162313, 0.8275063 , 0.66095809]],

       [[0.47881454, 1.90786619, 2.86606669, 0.36845643, 2.13879541],
        [2.31169307, 0.52863449, 1.40930613, 2.81526782, 0.3968416 ],
        [0.0508047 , 0.70606368, 0.86222409, 2.21119255, 0.39005411]]])

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [49]:
d_max = d.max()
d_max

2.932463193357257

In [50]:
d_min = d.min()
d_min

1.0501753102570737

In [51]:
d_mean = d.mean()
d_mean

1.9968911134694787

In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [52]:
f = np.empty((2, 3, 5))
f

array([[[1.48770369, 0.44056061, 1.7733613 , 2.78625404, 1.91906958],
        [1.95577675, 0.95740886, 2.05676235, 1.22329048, 0.72395032],
        [0.33223035, 1.00441432, 2.01162313, 0.8275063 , 0.66095809]],

       [[0.47881454, 1.90786619, 2.86606669, 0.36845643, 2.13879541],
        [2.31169307, 0.52863449, 1.40930613, 2.81526782, 0.3968416 ],
        [0.0508047 , 0.70606368, 0.86222409, 2.21119255, 0.39005411]]])

In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
#17.Print d and f. Do you have your expected f?
''
"""
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [55]:
for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0][0])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

print(f)

[[[ 75.  25.  75.  75.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  75.  25.  25.]]

 [[ 25.  75. 100.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [  0.  25.  25.  75.  25.]]]


In [54]:
print(d)

[[[2.1544912  1.40046713 2.33068239 2.89165982 2.41705697]
  [2.43847451 1.79814857 2.4967198  1.98214049 1.62598577]
  [1.30844566 1.8315468  2.47080574 1.70370583 1.57756326]]

 [[1.43213038 2.41049333 2.93246319 1.33962085 2.54332918]
  [2.63961156 1.47275918 2.10438795 2.90654212 1.36376107]
  [1.05017531 1.61232746 1.72926664 2.58396013 1.35801112]]]


In [57]:
d = ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

f = np.empty((2, 3, 5))

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0][0])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

print(f)

[[[ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  25. 100.  25.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]]
