In [1]:
#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

In [4]:
np.__version__

'1.23.5'

In [5]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/borja/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/borja/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/borja/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/borja/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,A

In [6]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a = np.random.rand(2,3,5)

In [8]:
#4. Print a.

In [9]:
print(a)

[[[0.20470585 0.80625118 0.79922684 0.99204466 0.66857879]
  [0.44281363 0.01658967 0.532175   0.19051963 0.80981839]
  [0.03016688 0.3015942  0.15349944 0.97923751 0.02828665]]

 [[0.61366053 0.10068017 0.65489473 0.43670729 0.44115152]
  [0.17401602 0.10872366 0.18473049 0.48816884 0.23393067]
  [0.47919834 0.62436324 0.5262721  0.20036072 0.84846126]]]


In [10]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [11]:
b = np.ones((5,2,3))

In [12]:
#6. Print b.

In [13]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [15]:
b.size

30

In [16]:
a.size

30

In [17]:
a.size == b.size

True

In [18]:
#8. Are you able to add a and b? Why or why not?

In [19]:
m = a + b  #las dimensiones no coinciden

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [20]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [21]:
c = b.T 

In [22]:
c.shape

(3, 2, 5)

In [23]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [24]:
d = a + c.reshape(2,3,5)

In [25]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [26]:
print(a)


[[[0.20470585 0.80625118 0.79922684 0.99204466 0.66857879]
  [0.44281363 0.01658967 0.532175   0.19051963 0.80981839]
  [0.03016688 0.3015942  0.15349944 0.97923751 0.02828665]]

 [[0.61366053 0.10068017 0.65489473 0.43670729 0.44115152]
  [0.17401602 0.10872366 0.18473049 0.48816884 0.23393067]
  [0.47919834 0.62436324 0.5262721  0.20036072 0.84846126]]]


In [27]:
print(d) #ha sumado cada valor de una matriz por el valor en la misma posición de la otra matriz.

[[[1.20470585 1.80625118 1.79922684 1.99204466 1.66857879]
  [1.44281363 1.01658967 1.532175   1.19051963 1.80981839]
  [1.03016688 1.3015942  1.15349944 1.97923751 1.02828665]]

 [[1.61366053 1.10068017 1.65489473 1.43670729 1.44115152]
  [1.17401602 1.10872366 1.18473049 1.48816884 1.23393067]
  [1.47919834 1.62436324 1.5262721  1.20036072 1.84846126]]]


In [28]:
#12. Multiply a and c. Assign the result to e.

In [29]:
e = a * c.reshape(2,3,5)

In [30]:
print(e)

[[[0.20470585 0.80625118 0.79922684 0.99204466 0.66857879]
  [0.44281363 0.01658967 0.532175   0.19051963 0.80981839]
  [0.03016688 0.3015942  0.15349944 0.97923751 0.02828665]]

 [[0.61366053 0.10068017 0.65489473 0.43670729 0.44115152]
  [0.17401602 0.10872366 0.18473049 0.48816884 0.23393067]
  [0.47919834 0.62436324 0.5262721  0.20036072 0.84846126]]]


In [31]:
#13. Does e equal to a? Why or why not?

In [32]:
e == a #estás multiplicndo cada valor por 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [33]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [34]:
d_max = d.max()

d_max

1.9920446646787364

In [35]:
d_min = d.min()

d_min

1.016589668203468

In [36]:
d_mean = d.mean()

d_mean

1.4356942636630108

In [37]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [38]:
f = np.empty((2,3,5))

f

array([[[0.20470585, 0.80625118, 0.79922684, 0.99204466, 0.66857879],
        [0.44281363, 0.01658967, 0.532175  , 0.19051963, 0.80981839],
        [0.03016688, 0.3015942 , 0.15349944, 0.97923751, 0.02828665]],

       [[0.61366053, 0.10068017, 0.65489473, 0.43670729, 0.44115152],
        [0.17401602, 0.10872366, 0.18473049, 0.48816884, 0.23393067],
        [0.47919834, 0.62436324, 0.5262721 , 0.20036072, 0.84846126]]])

In [39]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
        
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100

In [40]:
#17. Print d and f. Do you have your expected f?

In [41]:
print(f)

[[[ 25.  75.  75. 100.  75.]
  [ 75.   0.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  25.  75.]]]


In [42]:
print(d)

[[[1.20470585 1.80625118 1.79922684 1.99204466 1.66857879]
  [1.44281363 1.01658967 1.532175   1.19051963 1.80981839]
  [1.03016688 1.3015942  1.15349944 1.97923751 1.02828665]]

 [[1.61366053 1.10068017 1.65489473 1.43670729 1.44115152]
  [1.17401602 1.10872366 1.18473049 1.48816884 1.23393067]
  [1.47919834 1.62436324 1.5262721  1.20036072 1.84846126]]]


In [43]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

In [45]:
f = np.empty((2,3,5)).astype(str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
        
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 'A'
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 'B'
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 'C'
            elif d[i,j,k] == d_min:
                f[i,j,k] = 'D'
            elif d[i,j,k] == d_max:
                f[i,j,k] = 'E'

In [46]:
print(f)

[[['A' 'B' 'B' 'E' 'B']
  ['B' 'D' 'B' 'A' 'B']
  ['A' 'A' 'A' 'B' 'A']]

 [['B' 'A' 'B' 'B' 'B']
  ['A' 'A' 'A' 'B' 'A']
  ['B' 'B' 'B' 'A' 'B']]]
